[package]
name = "scroller"
version = "0.1.3"
authors = ["Davide Giovannini"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
indicatif = "0.11"
edit-distance = "2.1"